### ISSUE TITLE
Pregledanje rada

### ISSUE THREAD

**Issue by IvanJevtic9** [MATF-RG17/RG036-war-plane#1]
Generalno odradio sam sve , mozda ima jos neki detalj al to je u principu to ... 
-Posto za pomeranje aviona koristim a i d , imam nekako los prelaz kada idem sa a na d il obratno , 
 (ne pomera odmah u levo ako sam pre toga drzao da ide u desno ) krene da ga pomera tek posle neke  sekunde , kako bih to mogao da resim ? 

Pozdrav

**Comment by ivan-cukic-matf** [comment]
Vidite #2
